server:
  port: ${service-port}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${database-url}
    username: ${database-username}
    password: ${database-password}
  jpa:
    hibernate:
      ddl-auto: ${jpa-ddl-auto}
    show-sql: ${jpa-show-sql}

lzx:
  zookeeper:
    server: 47.52.150.205:2181
    sessionTimeout: 30000